language: android
jdk: oraclejdk8

# 开启基于容器的Travis CI任务，让编译效率更高
sudo: false


android:
  components:
    # 构建项目所用的BuildTools版本
    - build-tools-29.0.0
    # 用来编译项目的SDK版本
    - android-29




before_script:
  - chmod +x gradlew


script:
  # 生成release apk包
  - ./gradlew assembleRelease
